
version: 1.0.0

client:
  organization: ca.org2.example.com
  logging:
    level: info
  cryptoconfig:
    path: ${WORKDIR}/configs/crypto-config
  credentialStore:
    path: "./configs/key/signcerts"
    cryptoStore:
      path: ./configs/key
  BCCSP:
    security:
      enabled: true
    default:
      provider: "SW"
    hashAlgorithm: "SHA2"
    softVerify: true
    level: 256

organizations:
   ca.org2.example.com:
     mspid: Org1MSP
     cryptoPath:  ./configs/key/signcerts
     certificateAuthorities:
      - ca.org2.example.com

certificateAuthorities:
  ca.org2.example.com:
    url: https://ca.org2.example.com:8054 #写如/etc/hosts域名中
    grpcOptions:
      ssl-target-name-override: tlsca.org2.example.com
    tlsCACerts:
      path: ${WORKDIR}/configs/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem
      client:
        key:
          path: ${WORKDIR}/configs/crypto-config/peerOrganizations/org2.example.com/tlsca/935ebf5280d763b24bb134938d5a206039ed0d7a6e373b4f21770d423bac3e87_sk
        cert:
          path: ${WORKDIR}/configs/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem
    registrar:
       enrollId: admin
       enrollSecret: adminpw
    caName: ca-org2
